### ISSUE TITLE
Cannot login with a different account

### ISSUE THREAD

**Issue by eterry1388** [net-angel/netangel-protection-android#1]
1. Sign into app for the first time
2. Sign out
3. Sign into the app with a different account

The login fails.  The only way I could get it to sign in successfully on the second account was to clear the cache and data on the app (in android settings) and to delete the files in "NetAngel Protection" directory.

Questions to think about:
- Should we allow the device to be associated with a different account by just signing in as a different user?
- Should we send an email to the original account owner asking for permission to disassociate the device?
- Should we save those files in a different location that can't be deleted so easily by the user?

**Comment by eterry1388** [comment]
@klinker24 I think we ought to allow the authenticated user to disassociate the device from their NetAngel Dashboard account.  That would allow a different account to sign into the app and associate the device with a different account.  However, we don't want to allow anyone to sign in with a different account on the Android app and have it automatically disassociate with the original account.  Otherwise a kid could create an account, sign in with his account, and successfully bypass the filter (he would have to be a cleaver kid).

So we should make it so that you have to sign into the app first, then disassociate the device from the account before it can be associated with a different account.

The files for auth and such should be placed in a private directory so the users can't just delete them.

Luke, do you feel this is the best way to handle this?  I'm open to ideas.

**Comment by klinker24** [comment]
Android has a file store called `SharedPreferences` that is only accessible by the application that created them. This is the normal way to save preferences in apps, or quick information that will be needed later.

I have not looked into the authentication and how that works yet, but this is how the [Config](https://github.com/net-angel/netangel-protection-android/blob/master/app/src/main/java/com/netangel/netangelprotection/util/Config.java) class works.

We can definitely lock down the app to the currently authenticated user, so that you cannot just create a new account and override the old one. There is already a "Sign out" button on the UI, I will have to explore more what this button is currently doing, and how the authentication in the app is currently working. Looks like the config is storing:

- a `client_id`, which would define the the unique user
- and a `secret_token`, which would be the authentication credential
- I assume that both of these, or the user's email address, could be used as unique identifiers for the user

I see the following flow for this process:

1. User installs the app and an "admin" logs in for the first time
2. This user's log in is saved in some way, whether that is simply the email, or the `client_id`, I don't think it matters, we just need a way to associate the "admin" user on the device, and store it for later.
3. Whenever the app is opened after this, we should ensure that only the "Admin" user is the one that is able to sign in. Right now, it seems like anyone could create an account on the web and use it to sign in.
4. If the "Admin" user isn't the one that signs in, we should block the login attempt.
5. If the "Admin" user is the one that signs in, we should allow them to go to the VPN toggle screen, like it currently does.
6. On that toggle screen, instead of a generic "Sign out" button, we should change it to say something like "Remove Account". If this button is pressed, we should alert that user that anyone can now sign into the app.


One thing to consider:

1. What if the "Admin" user forgets what email they used to sign into the account? They could just uninstall and reinstall to fix this issue. Although I would imagine a parent would only have a single account, so I don't think that this is a huge issue.

**Comment by eterry1388** [comment]
I like that flow.  Number 4 should already be somehow implemented (not sure how well it works though). From what I remember, once an admin first logs in, it permanently associates the device with that account, so no other user could ever log in.  But I'm sure we can find out quickly by just testing it out.

On your question, if the admin user forgets their credentials, they could reset their password on the NetAngel Dashboard.  They can also change their email address on their dashboard account.

**Comment by klinker24** [comment]
This is done with #28. I have implemented it as discussed. 

I also removed the file store completely, this was being used as a way to persist the logged in user across uninstalls, it seems. I am now just using the `SharedPreferences` as a secure storage space. There are a number of issues with that approach:

1. What if the user forgot what account they had logged in with? Uninstalling and reinstalling wouldn't do anything to help them and the device could not be re-associated with a new account, unless they knew to delete the saved files.
2. If a kid uninstalled the app, or cleared the app data, then they wouldn't need or want to log in again, so it isn't preventing them from doing anything
3. Required the storage permission, which is unnecessary in an app like this
4. Easy to delete those files if the user knew what they were looking for. Each app does have its on protected area to store files, not sure why these were placed on the external storage area, where anyone could access them

Preventing them from uninstalling the app (#12), is a much safer way to go on that issue.
