### ISSUE TITLE
Android app using large amounts of data

### ISSUE THREAD

**Issue by allieraej** [net-angel/netangel-protection-android#30]
Ticket #208

"Is there any reason why my NetAngel Android app would suddenly have used over 650 mb of my phone data last week sometime? If there was an update or some other data pushed to it, it would have been nice to be warned so I could be sure to be within a WiFi network when the data was needed."

@klinker24

**Comment by klinker24** [comment]
**Questions/comments about this:**

Could it be that the data is actually running through the VPN now, and that his phone is counting it as going through the NetAngel app? Do we know what device he uses? I don't think this is a likely culprit, though.

When I first saw this, I thought that #4 might be effecting it or that something was going wrong there. But the pull request for that issue has not even been merged yet, so that can't be the problem.

The only time that the app is talking to the internet directly (making API calls) is when they sign in, and with the [CheckInService](https://github.com/net-angel/netangel-protection-android/blob/master/app/src/main/java/com/netangel/netangelprotection/service/CheckInService.java), which runs every 15 mins. The app doesn't make any external requests.

---

**Idea 1:**

Could it be an issue with actually reconnecting to the VPN? The app has to make data connections to get the VPN connection running. Could it be that his device is constantly/quickly losing internet access, and in turn, losing access to the VPN, so it is always restarting the connection? 

If that is the case, should look into an [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff) method for restarting the connection? Obviously, the downside to a backoff on the restart of the connection, would be that the user is not always protected, but it could help protect from data spikes, such as this.

I could see this working with the following logic (arbitrary values):

- If they lose the connection within 5 mins of the last reconnect, then start the backoff at 1 min.
  - so the app wouldn't try to reconnect for another minute
- If they lose the connection within another 5 mins, then the backoff would kick up to 2 mins and the app wouldn't try to reconnect until that 2 mins is up.
- The time will keep doubling like that, until the connection has been active for more than 15 minutes, or something. At that time, the backoff would reset to 1 minute.

**Idea 2:**

Instead of restarting the VPN connection immediately, after losing it (whether that is going from LTE to WiFi, or just losing service for awhile), we could just wait 1-2 minutes for the connection to normalize, then open up a new VPN connection. Unfortunately, the same drawback applies here: the user will not be constantly connected, if their internet connection is spottier.

**Comment by allieraej** [comment]
@klinker24 He has a Samsung phone, if that helps. Is this a result of the new Android app update?

**Comment by klinker24** [comment]
Hard to say for sure, but yes, with the timing, it is probably because of the update. 

I imagine because the app is actually trying to stay connected to the VPN now, rather than just losing the connection and forgetting about it.

The ideas I posted above are about the adjustments we can make, but they aren't really user-related, they are all things that will have to be done on the apps side, so I am not sure what to tell the customer about this one..

**Comment by allieraej** [comment]
No, this is a new problem. I haven't had any comments about this particular issue. I'll be sure to keep you updated if I receive any more. Thank you!

**Comment by klinker24** [comment]
I put in a few changes that should account for this issue, in PR #31. 

1. The VPN will wait 2 mins if it gets randomly disconnected, before attempting to connect again. This will ensure that the connection stabilizes, if it needs to.
2. Fixed an issue where the app would make multiple consecutive attempts to connect. All of these attempts would fall on top of each other and none of them would be successful. The app would have continued to restart the connection over and over, as long as the app was in memory. I also have a description of the change in the commit message: https://github.com/net-angel/netangel-protection-android/pull/31/commits/b7b0e52df664ef2aa2c291be023e94786d08370a

I am going to make a system of retries for #21, then this PR should be ready to merge, and we can hopefully close this issue and continue to monitor it, over the next few weeks.

**Comment by klinker24** [comment]
Have we seen any more issues around this? NetAngel has used less than 20 MB of my data this month, is all.

**Comment by allieraej** [comment]
I haven't heard back from the customer about this issue, but no one else has had any complaints or concerns with data usage.

**Comment by eterry1388** [comment]
Well, I keep reinstalling the app, so I am less than helpful.  But over 3 or 4 days, the app has used 10 mb.
