### ISSUE TITLE
Onboarding Wizard - Prompt for device name

### ISSUE THREAD

**Issue by eterry1388** [net-angel/netangel-protection-android#33]
As part of the onboarding wizard, add the ability to put in the device name.  It should default to the device name as we use it today (I think it's the model of the phone).

Here is an example from a different app:

![photo on 2-25-17 at 11 19 am](https://cloud.githubusercontent.com/assets/7739129/23333169/9b9f23b2-fb4c-11e6-997b-c175dc8fadf4.jpg)

**Comment by klinker24** [comment]
I have added this to the intro pager with this commit: https://github.com/net-angel/netangel-protection-android/pull/12/commits/59a83e54e4bc073c48cd33c8308a4d20a6c56ff0

![device name](https://cloud.githubusercontent.com/assets/4874287/23343978/e1d62806-fc39-11e6-9443-3da3d68c801e.png)

This isn't done just yet though. Since we do the login before showing the intro pager, the user can enter their device name, but the device has actually already been created, so the name isn't applied anywhere.

Currently:
1. The user logs into the app. 
2. With the login credentials, the backend will create the device, at this time
3. After the login is successful, the intro pager gets shown to the user. The second page is the one where they can insert their device name.
4. The user finishes the intro pager (by inserting a device name, enabling device admin, and turning on the VPN)
5. The intro pager quits to the main activity

After step 4, when the intro pager quits, this would be an ideal time to tell the backend that the user has changed their device name. This will be very easy on Android, but will require a new endpoint to update the device name, based on the device ID.

**Comment by eterry1388** [comment]
To update the device name:

`PUT` `/api/v1/devices/#{@client_id}`
`params = { "name": "my device" }`

**Comment by klinker24** [comment]
Ok, done with: https://github.com/net-angel/netangel-protection-android/pull/12/commits/8f445c50759bed9c7a7a36ea450725bc82afd7cb
