### ISSUE TITLE
If already connected to NetAngel, last screen of onboarding wizard fails

### ISSUE THREAD

**Issue by eterry1388** [net-angel/netangel-protection-android#36]
I upgraded my app on my phone to 2.0.0.  After signing in, it took me through the wizard (which is great so that device administrator could be enabled).  But on the last step, when I click the "Connect to NetAngel" button, the screen briefly blinks and returns back to the same screen.  I can't get past this final step.  I even closed the app, opening it again, and typed in my credentials again.  I went through the onboarding steps and got stuck on the last step again.

Only way to get past it was to "forget" the VPN in my android settings, then quickly open the app back up again and click that button.

We should fix this soon and get a 2.0.1 release out.

**Comment by eterry1388** [comment]
Nevermind on getting past the screen.  I opened the app again and it still get's stuck on the last step of the wizard.  Blarg.

**Comment by klinker24** [comment]
Ahh I know the issue here. It does check if the VPN is active (https://github.com/net-angel/netangel-protection-android/blob/master/app/src/main/java/com/netangel/netangelprotection/ui/fragment/EnableVpnAppIntroFragment.java#L22), but when it does, it just opens up the `MainActivity`, without telling the app that the setup pager should not come up again. 

I will make some changes shortly and make a PR for this.
